language: java
jdk: oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN: 495ce5ba-a814-4dbf-a3aa-560779e3b339
cache:
  directories:
    - $HOME/.m2
services:
  - memcached
