spring:
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      generate-ddl: false
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        format_sql: true
server:
  port: 8787
settings:
  deadline: "11:00"
  api_url:
    admin: "api/v1/admin/users"
    restaurants: "api/v1/restaurants"
    profile: "api/v1/users"

